AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    DynamoName:
        Type: String
    DynamoKey:
        Type: String
      
Resources:
  DynamoJaiden:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: !Ref DynamoKey
        AttributeType: S
      KeySchema:
      - AttributeName: !Ref DynamoKey
        KeyType: HASH
      SSESpecification:
        SSEEnabled: true
Outputs:
  DynamoJaiden:
      Value: !Ref DynamoJaiden
      Export:
        Name: DynamoJaiden
  DynamoJaidenArn:
      Value: !GetAtt DynamoJaiden.Arn
      Export:
        Name: DynamoJaidenArn